version: "3.4"

services:
  client:
    image: acblog/wasm-host:latest
    ports:
      - "6000:80"
    volumes:
      - ./client/appsettings.json:/app/appsettings.json
      - ./client/manifest.json:/app/wwwroot/manifest.json
      - ./client/background.jpg:/app/wwwroot/background.jpg
      - ./client/icon.png:/app/wwwroot/icon.png
    depends_on:
      - api
  api:
    image: acblog/api:latest
    ports:
      - "6100:80"
    environment:
      - ConnectionStrings:IdentityConnection=Server=db;User=sa;Password=MyPassword001;Database=api_identity;
      - ConnectionStrings:DefaultConnection=Server=db;User=sa;Password=MyPassword001;Database=api_default;
    volumes:
      - ./api/appsettings.json:/app/appsettings.json
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=MyPassword001
      - ACCEPT_EULA=Y
    volumes:
      - data:/var/opt/mssql
    ports:
      - "1433:1433"
volumes:
  data: