version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: "/src/AcBlog.Client.WebAssembly"
    schedule:
      interval: daily
    allow:
      - dependency-type: production
    open-pull-requests-limit: 3
  - package-ecosystem: "docker"
    directory: "/src/AcBlog.Client.WebAssembly"
    schedule:
      interval: daily
  - package-ecosystem: "docker"
    directory: "/src/AcBlog.Client.WebAssembly.Host"
    schedule:
      interval: daily
  - package-ecosystem: "docker"
    directory: "/src/AcBlog.Server.API"
    schedule:
      interval: daily
